name: Build and test the application with gradle

on:
  push:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Pull the git repository
      - uses: actions/checkout@v4
      # Download and install Java
      - name: Set up Java Development Kit 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Setting up gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      # Build the project
      - name: Build the application with gradle
        run: ./gradlew build