name: Build and test the application with gradle and build and push a docker image from it

on:
  push:
    branches: [ "master", "dev" ]

env:
  IMAGE_NAME: alystor/perfectify

jobs:
  build_gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Pull the git repository
      - uses: actions/checkout@v4
      # Download and install Java
      - name: Set up Java Development Kit 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Setting up gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      # Build the project
      - name: Build the application with gradle
        run: ./gradlew build
      # Copy the jar file
      - name: Copy jar file
        run: mv build/libs/perfectify-backend.jar app.jar
      # Upload it as artifact to use in docker build
      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: app.jar

  build_docker_file_and_push:
    needs: [ "build_gradle" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: app.jar

      # Setting up docker buildx
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      # Logging in to the github package registry
      - name: Log into registry github registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
      # Extracting the metadata for docker
      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          path: "."

      # Building and publishing the docker image
      - name: Build and push docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
